

services:
  proxy:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'    # Admin panel
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    env_file:
      - .env
    depends_on:
      - frontend
      - backend

  backend:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '5010:5000'
    command: node server.js

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '3000:80'
